apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: nginx
spec:
  containers:
    - name: nginx
      image: sajedul5/task_devops:v1
      ports:
        - containerPort: 80
